### ISSUE TITLE
unclear instructions: how to find session ID?

### ISSUE THREAD

**Issue by albx79** [magusbr/brickoptimizer#1]
The readme says: "It can be obtained by viewing the source from any store buying form".

Can you clarify what a "store buying form" is, and how to get there? I clicked on Buy -> Browse, then clicked on a random shop, and then on a random item. The resulting page has frames, and the innermost frame, with the form, is missing the b="..." attribute in the form tag.

**Comment by magusbr** [comment]
A buying foram is any page where the "add selected items to shopping cart"
button is present.

This page will most probably be framed. You'll have to get the "b" value
from the frame where this button is. This is indeed a boring task, but
could only be avoided if Bricklink provided a API.

Try opening this page after you have logged in to Bricklink to get the
session ID:

http://www.bricklink.com/storeDetail.asp?pg=1&h=13266&itemIDseq=3318

Hope this helps.
Best regards
